#!/usr/bin/bash
if [[ $# == 0 ]]; then exit 1; fi

function Build {
    echo "Assembling library..."
    cmake ./cmake && cmake --build ./cmake;

    echo "Creating package ..."
    cmake --build ./cmake --target package;
}

function Clean {
    echo "Clearing binary files ..."
    cd ,/cmake || exit
    rm -rf !(CMakeLists.txt)
    cd ..
}

if [[ $1 == "build" ]]; then Build; fi
if [[ $1 == "clean" ]]; then Clean; fi
exit 0
