name: C/C++ CI for Light

on:
  push:
    branches: [ "light-main" ]
  pull_request:
    branches: [ "light-main" ]

jobs:
  my_job:
    name: Standart work check
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: Test build
      run: make -C test/
    - name: Test run
      run: test/out/test_task_1
